### PR TITLE
Added Support for CDH 5.9 (Hbase 1.2.0-CDH5)

### PR DESCRIPTION
**Pull request by devaudio**
Just added support in for Hbase 1.2.0

### CODE REVIEW

**Comment by meniku** [comment]
Thanks a lot, this looks great.

However, why did you remove the installation instructions from the readme?

**Comment by devaudio** [comment]
D'oh sorry, don't merge that. I just took out the variant one instructions for people that grabbed it locally, from my fork. Didn't mean for that to be in the pull request. I am not great with git :-D

**Comment by devaudio** [comment]
or merge it, then restore it... those instructions are for people who ONLY want the CDH-5.9 stuff

**Comment by amithkanand** [comment]
@devaudio: Any specific reason to not use vanilla `HBASE`?

**Comment by devaudio** [comment]
Nope, can use vanillas

I already had other spark stuff where i specifically had CDH objects, so when i copied/pasted, just kept the -CDH  but there isn't anything that is CDH specific

**Pull request closed without merging**
